apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask
    tier: frontend
spec:
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  selector:
    app: flask-app-pod
    tier: frontend
